/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalaryRouteImport } from './routes/salary'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PressRouteImport } from './routes/press'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiMatchRouteImport } from './routes/ai-match'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as CompaniesSlugRouteImport } from './routes/companies.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaryRoute = SalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMatchRoute = AiMatchRouteImport.update({
  id: '/ai-match',
  path: '/ai-match',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const CompaniesSlugRoute = CompaniesSlugRouteImport.update({
  id: '/companies/$slug',
  path: '/companies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-match': typeof AiMatchRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/guides': typeof GuidesRoute
  '/help': typeof HelpRoute
  '/jobs': typeof JobsRouteWithChildren
  '/press': typeof PressRoute
  '/profile': typeof ProfileRoute
  '/salary': typeof SalaryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-match': typeof AiMatchRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/guides': typeof GuidesRoute
  '/help': typeof HelpRoute
  '/jobs': typeof JobsRouteWithChildren
  '/press': typeof PressRoute
  '/profile': typeof ProfileRoute
  '/salary': typeof SalaryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/companies': typeof CompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-match': typeof AiMatchRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/guides': typeof GuidesRoute
  '/help': typeof HelpRoute
  '/jobs': typeof JobsRouteWithChildren
  '/press': typeof PressRoute
  '/profile': typeof ProfileRoute
  '/salary': typeof SalaryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/companies/$slug': typeof CompaniesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-match'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/dashboard'
    | '/guides'
    | '/help'
    | '/jobs'
    | '/press'
    | '/profile'
    | '/salary'
    | '/sitemap.xml'
    | '/companies/$slug'
    | '/jobs/$id'
    | '/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-match'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/dashboard'
    | '/guides'
    | '/help'
    | '/jobs'
    | '/press'
    | '/profile'
    | '/salary'
    | '/sitemap.xml'
    | '/companies/$slug'
    | '/jobs/$id'
    | '/companies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-match'
    | '/blog'
    | '/careers'
    | '/changelog'
    | '/contact'
    | '/dashboard'
    | '/guides'
    | '/help'
    | '/jobs'
    | '/press'
    | '/profile'
    | '/salary'
    | '/sitemap.xml'
    | '/companies/$slug'
    | '/jobs/$id'
    | '/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiMatchRoute: typeof AiMatchRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  GuidesRoute: typeof GuidesRoute
  HelpRoute: typeof HelpRoute
  JobsRoute: typeof JobsRouteWithChildren
  PressRoute: typeof PressRoute
  ProfileRoute: typeof ProfileRoute
  SalaryRoute: typeof SalaryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CompaniesSlugRoute: typeof CompaniesSlugRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salary': {
      id: '/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof SalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-match': {
      id: '/ai-match'
      path: '/ai-match'
      fullPath: '/ai-match'
      preLoaderRoute: typeof AiMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/companies/$slug': {
      id: '/companies/$slug'
      path: '/companies/$slug'
      fullPath: '/companies/$slug'
      preLoaderRoute: typeof CompaniesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiMatchRoute: AiMatchRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  GuidesRoute: GuidesRoute,
  HelpRoute: HelpRoute,
  JobsRoute: JobsRouteWithChildren,
  PressRoute: PressRoute,
  ProfileRoute: ProfileRoute,
  SalaryRoute: SalaryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CompaniesSlugRoute: CompaniesSlugRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
